### ISSUE TITLE
Set async error on control using effect

### ISSUE THREAD

**Issue by gablemire** [MrWolfZ/ngrx-forms#10]
I'm currently trying to set an async error on a control using an effect. I would like, for instance, to check if a control is unique. I tried several things, but none worked. This is one of the tries I made using an effect.

     @Effect() asyncValidateForm$: Observable<Action> = this.action$
      .ofType(MarkAsSubmittedAction.TYPE)
      .filter((action: MarkAsSubmittedAction) => action.controlId === FORM_ID)
      .delay(2000)
      .map(() => {
        const errors: ValidationErrors = {
          duplicated: true
        };

        return new SetErrorsAction(`${FORM_ID}.id`, errors);
      });

I tried the following:
 - Setting the `controlId` to: FORM_ID.controlId using a flat error object.
 - Using the name of the controlId in the error object.
 - Using the name of the controlId prefixed with an underscore in the error object (with FORM_ID as the controlId).

There seem to be code to handle the last case, but an `if` statement prevents me from reaching that code. Is there a way to do it?

**Comment by MrWolfZ** [comment]
Your good looks already pretty correct to me. However, I need some more info. Could you please post your form value's interface? Also, do you want to set the error on the top level form group or some child control? As a general hint what I do to set errors asynchronously is to access the control ID from the state itself instead of building it myself. This makes the code more independent of the internals of ngrx-forms. So my version of your code would look like this:

```typescript
@Effect() asyncValidateForm$: Observable<Action> = this.action$
  .ofType(MarkAsSubmittedAction.TYPE)
  .map(action => action as MarkAsSubmittedAction)
  .withLatestFrom(this.store.select(s => s.path.to.formState))
  .filter(([action, formState]) => action.controlId === formState.id)
  .delay(2000)
  .map(([_, formState]) => {
    const errors: ValidationErrors = {
      duplicated: true
    };

    return new SetErrorsAction(formState.controls.childControl.id, errors);
  });
```

Maybe this helps already. Otherwise I'll try to provide a more complete example. However, that'll have to wait until I get back home from work (it's morning here right now).

**Comment by gablemire** [comment]
Ok, so I continued investigating and I found the problem. I was using `updateGroup` with synchronous validation on the field I was trying to put in error asynchronously. The validate function removes all errors on a field if there are no synchronous errors.
