### ISSUE TITLE
How to use with optional model attributes and how to initialize default values?

### ISSUE THREAD

**Issue by jimjaeger** [MrWolfZ/ngrx-forms#103]
Hey,

I am working with ng-forms and ng-reactive forms for a while by using service model and entities in the forms (service entry == form model). A observable set a service entry in a UI component and the UI component set default values, manage the form state and emit the save value as output. The form manage the update by using formGroup and formControlName attributes.

As I use ngrx-store, ngrx-entities and ngrx-effects in the rest of the application I look into ngrx-forms to manage the form state and validate input with sync and async validation.

The examples looked quite simple but they do not show any recommendation how to handle optional model attributes. The UI throw an error in cases the value is not available. Should I set empty strings for not available optional attributes? Can you explain where in the validation logic I should set it?
Additionally can you explain where I should set default values for new form model attributes?

Thanks in advance.

**Comment by MrWolfZ** [comment]
Sorry for the late response. Optional controls are fully supported. In your form value interface you should declare the property as optional and then not provide this property when setting the initial form value. You need to be aware that the whole control, not just its value, will not be present in the form state. Therefore, if you have a control that is not set you must not use that control in a `[ngrxFormControlState]` binding, since that will throw an error. So best just simply add `*ngIf="formState.controls.myOptionalControl"` on that form element.

Any validation logic defined for that control will only be run if the control exists. If you want to validate that the control exists in certain scenarios you should place the validation logic into the parent form group, in which you can check for the presence or absence of the control.

I'm not sure what you mean regarding the default values. Could you please clarify?

**Comment by jimjaeger** [comment]
Hi Jonathan,

thanks for the answer.

Usually I have the following form usecases:
- Use a `new form value` to create an new back end object (POST)
- Use `existing form value` loaded by a service to update the back end object (PUT)

For these usecases I have the following field cases:
- `Optional fields`: Optional fields are fields that defined as optional in the form value interface, and can be undefined.  You are right, one way to display optional fields would be to hide the field if the value is not defined. But this would prevent that a user can set the a value. I prefer to show such fields as empty input field.  In case of angular reactive forms I set for such fields an empty string value for the initial model and patch an existing entity on top at `ngOnChanges` event. As result such fields are in every case defined and they can be displayed. At save action I remove the emtpy string for optional fields. It works for the new form value and existing form value use case.  I guess there is no out of the box support and I need to simulate similar behavior here as well.  Is it correct? If yes, where can you recommend to do it? Can you give an example?
- `Default values for empty fields`: Default values are values that will be set if a value of an field is not defined or empty. That I use to pre-fill form input fields with default values or pre-select an option to help a user with common values / selections.  In case of angular reactive forms I set these values in the initial model and patch an existing entity on top at `ngOnChanges` event.  As result such fields have the default or the value from the existing form value. The default value would be set in every case the value is not defined, means also if the value is empty at  `ngOnChanges` event after the user cleaned it out in the form.  It works for the new form value and existing form value use case. I am not sure where I should set such default values that can be used for new and existing form values. Should I add such function in the validation logic? Where can you recommend to do it?
- `Derived fields`: Derived fields are fields they are derived from value/state of other fields. In contrast to the default values the derived fields usually are initiated once the form value is set the first time. For example you have a attribute `field1` text field and a derived field boolean `field1Enabled`. The `field1Enabled` will be used for a checkbox to enable and disable the textfield. So the user can set the value by clicking on the checkbox. But the inital state of the checkbox is derived from if the textfield is empty or not. Where can you recommend to do it?
- `Hide or disable fields for existing form values`: It is also usual for my forms to hide or disable input fields for existing form values. For example the unique name entered at the creation time but readonly after the object has been created. In case of angular reactive forms I usually detects at  `ngOnChanges` if the form is new or exists by checking the ID and set a component property to be able to use it in the html template to hide or disable the form field. I guess this I can do now in the reducer validation. Is it correct?

Currently I try to migrate an existing angular reactive form to the reducer approach but struggle because I am not sure where in the flow I have to add such field case logic. For example currently I added the initialization and derivation like this:
` this.formStore.dispatch( exists ? new SetValueAction<FormValue>(FORM_ID, {
              ...initialState.value, optional1Enabled: !!t.optional1, ...t }) : new SetValueAction<FormValue>(FORM_ID, { ...initialState.value })     )   );`
Also I created such reducer validation functions like: 
`const enableByParentState = (fn: (value: any) => boolean) =>
  function<TValue extends FormControlValueTypes>(
    state: FormControlState<TValue>,
    parentState
  ): FormControlState<TValue> {
    if (fn(parentState)) {
      return enable(state);
    } else {
      return disable(state);
    }
  };`


or `optional2Enabled: (state, parentState) => parentState.value.optional2 && parentState.value.optional2 != -1 ? setValue(state, true) :state`

All feel a little ugly. Do you have an example app for supporting the use cases above?

-----------------------------
This is a sample form value interface and form for the description:
const formValue: {
  id:string;
  mandatory1: string;
  mandatory2: string; <-- default value "m2"
  optional1?: string;
  optional1Enabled?: boolean;
  optional2?: number;
  optional2Enabled?: boolean;
}

form for new :
Input ID:  [    ]
Input mandatory1:  [    ]
Input mandatory2:  [ m2  ]
Input optional1: [  ] [    ]
Input optional2: [  ] [    ]

form for existing:
Input ID:  IDABCDE <-- no input field anymore
Input mandatory1:  [ m1  ]
Input mandatory2:  [ m3  ]
Input optional1: [X] [ op1  ]
Input optional2: [    ]

**Comment by MrWolfZ** [comment]
Once again, sorry for the late response (I've had some very busy work weeks).

I always recommend placing as much logic as possible in the reducer. So instead of having logic in your components or services that dispatch form-modifying actions I would create a dedicated reducer for the form state and create actions for initializing it for new and existing objects. So you could do it like this:

```typescript
import { Action } from '@ngrx/store';
import {
  Actions as NgrxFormsActions,
  createFormGroupState,
  disable,
  enable,
  formStateReducer,
  setValue,
  updateGroup,
  validate,
} from 'ngrx-forms';
import { required } from 'ngrx-forms/validation';

export interface MyObject {
  id: string;
  mandatory1: string;
  mandatory2: string;
  optional1: string | null;
  optional2: number | null;
}

export interface MyObjectFormValue {
  id: string;
  mandatory1: string;
  mandatory2: string;

  // as you suggest, instead of making the whole control optional,
  // leave it always in the form state and treat an empty input value
  // (which may be '' or null depending on the browser) as the
  // field not being filled
  optional1: string | null;
  optional1Enabled: boolean;
  optional2: number | null;
  optional2Enabled: boolean;
}

export const EMPTY_FORM_VALUE: MyObjectFormValue = {
  id: '',
  mandatory1: '',
  mandatory2: '',
  optional1: null,
  optional1Enabled: false,
  optional2: null,
  optional2Enabled: false,
};

export class InitializeMyObjectFormForNewObjectAction implements Action {
  type: 'initialize my object form for new object';
}

export class InitializeMyObjectFormForExistingObjectAction implements Action {
  type: 'initialize my object form for existing object';

  constructor(
    public myObject: MyObject,
  ) { }
}

export type MyObjectFormActions =
  | InitializeMyObjectFormForNewObjectAction
  | InitializeMyObjectFormForExistingObjectAction
  ;

export const FORM_ID = 'my form';

// in this function we can place all logic regarding default values and derived fields
export const updateForm = updateGroup<MyObjectFormValue>({
  mandatory2: mandatory2 => {
    if (mandatory2.value) {
      return mandatory2;
    }

    // from your description I understood that the default value should always be
    // set when the field is empty, i.e. also when the user clears the input manually;
    // this function will ensure that happens, however, it will do so immediately while
    // the user is typing, which may be confusing for the user; an alternative would be
    // to set the default value when the input loses focus; this can be achieved here
    // as well by checking if the control has focus and only set the value if it doesn't;
    // note that you have to enable focus tracking on the input for this to work properly,
    // i.e. use `[ngrxEnableFocusTracking]="true"` and then replace the below line with
    // `return mandatory2.isUnfocused ? setValue(mandatory2, 'm2') : mandatory2;`
    return setValue(mandatory2, 'm2');
  },

  // these two functions ensure the inputs are always enabled or disabled in sync with the
  // checkbox values
  optional1: (optional1, parentState) =>
    parentState.value.optional1Enabled ? enable(optional1) : disable(optional1),
  optional2: (optional2, parentState) =>
    parentState.value.optional2Enabled ? enable(optional2) : disable(optional2),
});

// in this function we can place all validation logic; we could also put the validation
// logic into the `updateForm` function but this way both concerns are more clearly
// separated
export const validateForm = updateGroup<MyObjectFormValue>({
  mandatory1: validate(required),
  // we don't need to validate `mandatory2` since the update function above ensures
  // it always has a value
});

export const INITIAL_FORM_STATE = validateForm(
  updateForm(createFormGroupState(FORM_ID, EMPTY_FORM_VALUE))
);

export function myObjectFormReducer(
  formState = INITIAL_FORM_STATE,
  action: MyObjectFormActions | NgrxFormsActions<any>,
) {
  switch (action.type) {
    case 'initialize my object form for new object': {
      // the initial form state is already properly filled with default values and can be used
      // for initializing the form for new objects
      return INITIAL_FORM_STATE;
    }

    case 'initialize my object form for existing object': {
      const myObject = (action as InitializeMyObjectFormForExistingObjectAction).myObject;

      // set the form value based on the provided object; we set the value on the initial
      // form state to ensure the state is pristine
      formState = setValue<MyObjectFormValue>(INITIAL_FORM_STATE, {
        ...myObject,
        optional1Enabled: !!myObject.optional1,
        optional2Enabled: myObject.optional2 !== null && myObject.optional2 !== -1,
      });

      // disable all input fields that should not be editable for existing objects;
      // you can then check the `isDisabled` property in the HTML and show the field
      // as read-only
      formState = updateGroup(formState, {
        id: disable,
      });

      // finally apply our update function to set default values and also validate the form
      return validateForm(updateForm(formState));
    }

    default:
      return validateForm(updateForm(formStateReducer(formState, action)));
  }
}
```

Inside your component's `ngOnChanges` you can then simply dispatch either of the initialization actions based on whether there is an existing object or it is a new object.

I hope this answers all of your questions. If you have any more questions I am always happy to help.

**Comment by jimjaeger** [comment]
Thanks for your answer with the detailed example.

I like the separation approach. It took a while to move everything. I created actions to init by new or existing entry and separated also the validation for existing and new to creating entries in different functions.  I also looked into your example for asynchronous validation and added the validation for some email fields to validate if the email address exists in the backend.  

Based on the move I have some further questions and I am not sure if we want to follow up here, or if your prefer a new issue or an email conversation.

Following aspects:
* After I moved all I still have the case that I have to prefill optional fields with empty strings to be able to get input fields without error and so I have to filter the empty strings and remove the property from the entry before sending it to the service. The reason for it is that the POST request to the server should not contain the property when the user does not enter a value. In the previous approach I had the original server entry available and could compare to decide if a value should be really a "" string or should be removed. Do you have an idea how I can realize it here?

* The described approach for async validation show effects that attach to every change in the store. As result the validation also will be executed when I change a different field. Do you have an idea how to isolate the validation only to change for the specific email field. Usually effects filter to a dedicated action to be executed. Is there any action that is triggered when a specific field is updated? Or I also could userDefinedProps that store the last verified value and compare it with every call.

* To be able to use the async validation for several email control I transport the related control via the general validate action so I can access in the reducer the id and correlate the validation result with the control. In this case I would like use the control Id to access the child state. Do you have a helper function to get access to the correct child state?

* I would reuse update state functions like  value: (state, parentState) => (parentState.value.id !== '-1' ? enable(state) : disable(state)) for different fields but every time I move it into a function and use the function in the reducer, the typescript compiler say it is invalid. Do you have an idea how to do?

Really appreciate your help.

Thanks in advance.

**Comment by MrWolfZ** [comment]
I think discussing this here is just fine since other people might benefit from it. However, if you want to share some code examples that you don't want to post here feel free to email me.

Regarding your first point, I'm not sure I understand. Do the optional fields also have a `required` validation? If not `undefined` as a value should work just fine. If they have that validation, then why? Obviously they are not required. Or do you have some other validation rules for these fields that cause them to error when undefined?

Regarding your second point, there are multiple ways of doing it. If you want to validate a single form control you can just `select` it like in the example, i.e. `select(s => s.myFormState.controls.asyncControl)`, and then do the rest of what the example does. However, as you mention there is indeed a dedicated action for updating a form field: `SetValueAction`. You can subscribe to these and filter based on the ID of the control, e.g. `this.actions$.pipe(ofType(SetValueAction.TYPE), map(a => a as SetValueAction), filter(a => a.controlId === INITIAL_FORM_STATE.controls.asyncControl.id))` (or just hardcode the ID, it will always be `formId.controlId.nestedControlId` etc.). However, this of course only works for value changes that are triggered from the HTML. If the value changes as a result of the reducer (e.g. due to the mandatoriness logic from my example) then no action is dispatched and only the first version of subscribing to the store will work.

Regarding your third point, you can construct the ID similarly to what I described just above. Alternatively you can use `updateGroup` with a computed property to get a similar effect, e.g. `updateGroup<MyFormValue>(formState, { [controlName]: setAsyncError('foo', { bar: true }) })`. However, if you already have the full control ID in the action you can also just manually call the `formStateReducer` with the correction action, i.e. call `formStateReducer(formState, new SetAsyncErrorAction(action.controlId, 'foo', { 
bar: true }))`.

For your fourth point, could you please post the concrete compiler error? Make sure you properly type the function. You can import `ProjectFn2` from `ngrx-forms` for this. So in your case something like this:

```typescript
export const enableOrDisableStateBasedOnParentIdValue: ProjectFn2<FormControlState<string>, FormGroupState<MyFormValue>> = (state, parentState) => parentState.value.id !== '-1' ? enable(state) : disable(state);
```

**Comment by MrWolfZ** [comment]
Closed due to inactivity. If you have any more questions please open a new issue.
