### ISSUE TITLE
material select doesn't show initial value if mat-options are provided asychronously

### ISSUE THREAD

**Issue by fxck** [MrWolfZ/ngrx-forms#108]
Using the `NgrxMatSelectViewAdapter` fix from the example app. If i'm loading data for mat-option asynchronously, it doesn't show the selected value.

**Comment by fxck** [comment]
@MrWolfZ took a while, but here's reproduction https://stackblitz.com/edit/material2-ngrx-forms?file=src%2Fapp%2Fapp.component.ts

**Comment by MrWolfZ** [comment]
Thank you very much for taking the time to create the reproduction. Indeed, I have encountered this issue before myself. While I would classify this as an issue with angular material (since it should be responsible for ensuring the current value stays or becomes selected when the options change) you prompted me to re-consider whether this can be solved in the view adapter. As it turns out, it can be done. Below you can find an updated version of the view adapter. Could you please test whether this works for you? These custom material adapters are not officially part of the library (although maybe they should with an extra material compatibility package?) and they are difficult to test so it would be great to have some feedback.

```typescript
import { AfterViewInit, Directive, forwardRef, OnDestroy } from '@angular/core';
import { MatSelect } from '@angular/material/select';
import { FormViewAdapter, NGRX_FORM_VIEW_ADAPTER } from 'ngrx-forms';
import { Subscription } from 'rxjs';

// tslint:disable:directive-selector
// tslint:disable:directive-class-suffix
// necessary since material 2 does not properly export the mat-select as a NG_VALUE_ACCESSOR
@Directive({
  selector: 'mat-select[ngrxFormControlState]',
  providers: [{
    provide: NGRX_FORM_VIEW_ADAPTER,
    useExisting: forwardRef(() => NgrxMatSelectViewAdapter),
    multi: true,
  }],
})
export class NgrxMatSelectViewAdapter implements FormViewAdapter, AfterViewInit, OnDestroy {
  private value: any;
  private subscriptions: Subscription[] = [];

  constructor(private matSelect: MatSelect) {}

  ngAfterViewInit() {
    this.subscriptions.push(
      this.matSelect.options.changes.subscribe(() => {
        this.setViewValue(this.value);
      })
    );
  }

  ngOnDestroy() {
    this.subscriptions.forEach(s => s.unsubscribe());
  }

  setViewValue(value: any) {
    this.value = value;

    // we have to verify that the same value is not set again since that would
    // cause focus to get lost on the select since it tries to focus the active option
    const selectedOption = this.matSelect.selected;

    if (selectedOption) {
      if (Array.isArray(selectedOption) && Array.isArray(value)) {
        if (value.length === selectedOption.length && value.every((v, i) => v === selectedOption[i])) {
          return;
        }
      } else if (!Array.isArray(selectedOption)) {
        if (value === selectedOption.value) {
          return;
        }
      }
    }

    // because the options are potentially updated AFTER the value (because of their order in the DOM),
    // setting the value has to be deferred, otherwise we might select an option which is not available yet.
    Promise.resolve().then(() => this.matSelect.writeValue(value));
  }

  setOnChangeCallback(fn: any) {
    this.matSelect.registerOnChange(value => {
      this.value = value;
      fn(value);
    });
  }

  setOnTouchedCallback(fn: any) {
    this.matSelect.registerOnTouched(fn);
  }

  setIsDisabled(isDisabled: boolean) {
    this.matSelect.setDisabledState(isDisabled);
  }
}
```

**Comment by fxck** [comment]
You mention in some other issue you already brought it up with them, can you link me to that issue / comment? I'll try to weigh in.

**Comment by MrWolfZ** [comment]
[Here](https://github.com/angular/material2/issues/6549)'s the link where I had asked them to export the control value accessor instead of hard-coding the dependency on @angular/forms.

**Comment by MrWolfZ** [comment]
To be clear though, the behaviour I mentioned above (i.e. options not becoming selected when they are set after the value) is not something I have created a bug report for yet. It's been some time since I really looked into it, but if I remember correctly the issue was that the value of the mat select is reset (or not set at all) if no matching option exists. So the problem is not only when you set the options asynchronously, it also exists when you change the options after they have been set.
