### ISSUE TITLE
Missing support of Date types: "Date values are not supported. Please used serialized strings instead."

### ISSUE THREAD

**Issue by pajarito80** [MrWolfZ/ngrx-forms#12]
Hello 

First, thank you very much for bringing ngrx-forms to the community. It seems for me to be the right way in combination of using a store.

We created some forms and they seem to work pretty well - except for date values. If the form control value is of type Date, the data will not be set but the reducer throws an error: Date values are not supported. Please used serialized strings instead.

If I comment out this line of code in the setValueReducer function of ngrx/forms, everything seems to work normally:

   /*if (action.payload.value instanceof Date) {
        throw new Error('Date values are not supported. Please used serialized strings instead.');
    }*/

What is the reason for this restriction? Are there any side effects by using date types?

Thank you very much
Kind regards
Martin Cabalzar

**Comment by MrWolfZ** [comment]
@pajarito80 Very early on in the development of this library I made a design decision to have the shape of the from controls and groups be automatically determined from the initial form value. The reason was to keep as much as possible of the internal structure of `ngrx-forms` hidden. One consequence of this decision was that it is impossible to use any non-primitive value as the value for a form control.

Now to your concrete issue: since dates are objects and not primitives `ngrx-forms` will interpret them as  as a form group and create many control states (one per property of the date object). You can see this if you display your form state via `{{ formState | json }}`. While I could implement special handling for `Date` values, this would mean that a) the code would get much more complicated in many areas, and b) it wouldn't be the last such special case I'd have to implement. Especially for dates a lot of people are using moment.js or simliar libraries instead of pure JavaScript dates. In addition using objects like `Date` as values would cause issues with the serializability of the state, since when JSON serializing the state (as tools like the redux dev tools do) you lose all type information.

All of this lead me to implement a different solution for this problem in the form of value converters (you can read about them in the README). For dates `ngrx-forms` ships with a value converter that converts `Date` objects to ISO strings and back, so that it integrates properly (the README example for value converters shows exactly this use case).

I hope this answers your question.
