### ISSUE TITLE
Question: What is the purpose of FormState<T>

### ISSUE THREAD

**Issue by ilya-on-github** [MrWolfZ/ngrx-forms#146]
Hi!

First of all, thanks for your lib, it's very useful.

I have a question about FormState type. What is the purpose of it? As I understood there is a single base type AbstractControlState and several derived, such as FormControlState. Why do you use type constraints based on FormState and not on AbstractControlState?

For example, why this:
```
function formStateReducer<TValue>(state: FormState<TValue> | AbstractControlState<TValue> | undefined, action: Action): FormState<TValue>;
```
can't be written without using FormState:
```
function formStateReducer<TControlState extends AbstractControlState<TValue>, TValue extends FormControlValueTypes>(
  state: TControlState | undefined, action: Action): TControlState
```
?

The problem is If I want to use the reducer with FormControlState, I need explicitly cast result to FormControlState:

```
export function controlUpdateFn<T extends FormControlValueTypes, V>(): ProjectFn2<FormControlState<T>, FormGroupState<V>> {
  return (controlState, groupState) => {
    const action: Action = new SetUserDefinedPropertyAction(...);
    const newControlState: FormControlState<T> = formStateReducer(controlState, action); // error 'Type InferredFormState<InferenceWrapper<T>> is not assignable to type FormControlState<T>'

    return newControlState;
  };
}
```

The same problem occurs when I try to compose setUserDefinedProperty with validate:
```
export function requiredControl<T extends FormControlValueTypes, V>(): ProjectFn2<FormControlState<T>, FormGroupState<V>> {
  const controlUpdateFn: ProjectFn2<FormControlState<T>, FormGroupState<V>> =
    (controlState: FormControlState<T>) => {

      const state1: FormState<T> = setUserDefinedProperty(requiredKey, true)(controlState); // why FormState<T> instead of AbstractControlState<T>
      const state2: FormState<T> = validate<T>(required)(state1 as AbstractControlState<T>); // because of FormState I have to cast argument to AbstractControlState

      return state2 as FormControlState<T>; // and also I have to cast result back to FormControlState
    };

  return controlUpdateFn;
}
```
Why it can't be done this way?
```
function setUserDefinedProperty(name: string, value: any): <TControlState extends AbstractControlState<TValue>, TValue extends FormControlValueTypes>(state: TControlState) => TControlState;

function validate<TControlState extends AbstractControlState<TValue>, TValue extends FormControlValueTypes>(fn: ValidationFn<TValue>, ...rest: ValidationFn<TValue>[]): (state: TControlState) => TControlState;

export function requiredControl<T extends FormControlValueTypes, V>(): ProjectFn2<FormControlState<T>, FormGroupState<V>> {
  const controlUpdateFn: ProjectFn2<FormControlState<T>, FormGroupState<V>> =
    (controlState: FormControlState<T>) => {

      const state1: FormControlState<T> = setUserDefinedProperty(requiredKey, true)(controlState); // state1 is of type FormControlState
      const state2: FormControlState<T> = validate<FormControlState<T>, T>(required)(state1); // no need of explicit argument cast

      return state2; // also no need to cast the result
    };

  return controlUpdateFn;
}
```

Am I missing something?

**Comment by MrWolfZ** [comment]
Sorry for the late response. The purpose of `FormState` is that in the normal uses cases where you directly apply the functions to a state whose type is known, you do not need to care about the correct type.

However, as you point out, when you try to write some higher-level code that deals with generics itself it can force some ugly casts/explicit type annotations. However, those cases are much more rare than those where the type of the value is already known.

In regards, to your examples, sadly there is indeed a small thing you are missing. In your example you constrain the type of `TValue` to `FormControlValueTypes` which it can't be, since the update functions can be applied to arbitrary form states. However, if you remove that constraint the code doesn't compile, since it fails to properly infer the type of the value (copy paste the example below to see that).

Personally I believe that it is acceptable to have to write some more explicit type annotations in higher level functions like your `requiredControl`. If you had to use explicit annotations everywhere I would consider changing this.

```ts
unction setUserDefinedProperty(name: string, value: any): <TControlState extends AbstractControlState<TValue>, TValue>(state: TControlState) => TControlState {
  return undefined!;
}

function validate<TControlState extends AbstractControlState<TValue>, TValue extends FormControlValueTypes>(fn: ValidationFn<TValue>, ...rest: ValidationFn<TValue>[]): (state: TControlState) => TControlState {
  return undefined!;
}

export function requiredControl<T extends FormControlValueTypes, V>(): ProjectFn2<FormControlState<T>, FormGroupState<V>> {
  const controlUpdateFn: ProjectFn2<FormControlState<T>, FormGroupState<V>> =
    controlState => {
      const state1 = setUserDefinedProperty('required', true)(controlState);
      const state2 = validate<FormControlState<T>, T>(required)(state1);
      return state2;
    };

  return controlUpdateFn;
}
```

PS: your `controlUpdateFn` example works if you simply use `formControlReducer` instead, since you know the type of the control. The idea behind `formStateReducer` is once again to be used when you deal with a state with a known type.
