### ISSUE TITLE
Setting inputs to readonly

### ISSUE THREAD

**Issue by magnattic** [MrWolfZ/ngrx-forms#152]
Is it possible to set inputs to readonly?

I realize I could do this with user defined properties, but it might be a nice addition to the API. :)

**Comment by MrWolfZ** [comment]
Hmm, I don't really like this since not all HTML form elements provide the ability to make them readonly, which would make the API a bit inconsistent. I think this is enough of an edge case that implementing this yourself with user-defined properties should suffice. If more requests for such a feature appear I may reconsider.
