### ISSUE TITLE
Dynamic Form Arrays Questions

### ISSUE THREAD

**Issue by kt215** [MrWolfZ/ngrx-forms#157]
I have used ngrx-forms successfully in a project for a while now, but I'm unable to figure out how to use dynamic form elements correctly. I see code snippets here and there in both the documentation and closed issues, but I'm unable to piece it together.

Let's use this example as a reference:
https://ngrx-forms.readthedocs.io/en/master/user-guide/form-arrays/#dynamic-form-arrays

* How is `dynamicFormArray` initialized (initial state)?
* Why do you have both `DynamicObject` and `DynamicObjectFormValue` interface types?
* How to **update** and **validate** the `dynamicFormArray` elements?
* How do I iterate over dynamicFormArray in the HTML?
* What is the [ngrxFormControlState] path syntax in the HTML form to bind to `someNumber`?

**Comment by MrWolfZ** [comment]
> How is `dynamicFormArray` initialized (initial state)?

I assume you are already getting the data into the store somehow with an action (otherwise you can always create a new one). As part of this action you can create the form state. If you use ngrx 8 it could look like this:

```ts
import { createAction, createReducer, on, props } from '@ngrx/store';
import { createFormArrayState, FormArrayState, onNgrxForms } from 'ngrx-forms';

export interface DynamicObject {
  someNumber: number;
  someCheckbox: boolean;
}

export const initializeForm = createAction(
  'INITIALIZE_FORM',
  props<{ objects: DynamicObject[] }>(),
);

export interface State {
  someOtherState: string;
  dynamicForm: FormArrayState<DynamicObject>;
}

export const initialState: State = {
  someOtherState: 'some string',
  dynamicForm: createFormArrayState('dynamicForm', []),
};

export const reducer = createReducer(
  initialState,
  onNgrxForms(),
  on(initializeForm, (s, { objects }) => ({
    ...s,
    // this re-initializes the form completely, i.e. it resets
    // isTouched, isDirty etc; alternatively you can use setValue
    // to preserve that state
    dynamicForm: createFormArrayState(s.dynamicForm.id, objects),
  })),
);
```

> Why do you have both `DynamicObject` and `DynamicObjectFormValue` interface types?

Yeah, I agree that's pretty confusing. In general I prefer to declare separate interfaces for separate concerns, but in this case where the shape of the data is exactly the same using only a single interface is just fine.

> How to **update** and **validate** the `dynamicFormArray` elements?

To validate the form you first create a validation function:

```ts
import { updateArray, updateGroup, validate } from 'ngrx-forms';
import { greaterThan, required } from 'ngrx-forms/validation';

// updateArray applies the passed form update to all elements
export const validateForm = updateArray(
  // this is where we validate a single array element
  updateGroup<DynamicObject>({
    someNumber: validate(required, greaterThan(0)),
  }),
);
```

We can then wrap the reducer like this to call the validation whenever the form state is updated:

```ts
import { wrapReducerWithFormStateUpdate } from 'ngrx-forms';

export const reducerWithValidation = wrapReducerWithFormStateUpdate(
  reducer,
  s => s.dynamicForm,
  validateForm,
);
```

Form states are automatically updated when bound to HTML form elements. If you want to manually update the form state just create an action and a reducer that updates the form (similarly to how the validation above is done, i.e. via `updateArray` and `updateGroup`).

> How do I iterate over `dynamicFormArray` in the HTML?

The `controls` property of a form array is a normal array, so you can simply use `*ngFor`. For performance reasons I recommend using a tracking function that tracks by the group's ID.

```html
<div *ngFor="let group of dynamicForm.controls; trackBy: trackById">
```

> What is the `[ngrxFormControlState]` path syntax in the HTML form to bind to `someNumber`?

In this example the elements of the array are themselves form groups, i.e. each element has `controls`. Below you can see how to bind the controls of each group to HTML `input`s.

```html
<div *ngFor="let group of dynamicForm.controls; trackBy: trackById">
  <input type="checkbox"
         [ngrxFormControlState]="group.controls.someCheckbox" />
  <input type="number"
         [ngrxFormControlState]="group.controls.someNumber" />
</div>
```

I hope this answers all of your questions. If so, please close this issue, otherwise I'll happily answer any more questions you have.

**Comment by kt215** [comment]
Thank you for a very detailed response. I had to learn the new ngrx 8 features before I could understand most of your code :-)

In my case, the `State` is part a larger `AppState` like this:

```js
export interface AppState {
    formState: FormGroupState<State>; //State interface from your sample code.
}

export const reducers: ActionReducerMap<AppState, any> = { //Passed into StoreModule.forRoot()
    formState: reducerWithValidation, //reducerWithValidation from your sample code.
};
```
But, after upgrading to version 8 features and syntax, my existing `ngrxFormControlState` bindings fail with `undefined` errors. Any idea why? Using Ngrx Store DevTools, the store state looks correct. My reducer is defined like this:

```js
const _reducer = createReducer(
    initialState,
    onNgrxForms(),
    //action handlers omitted.
);

export const reducerWithValidation = wrapReducerWithFormStateUpdate(
    _reducer,
    state => state,
    validateForm
);
```

My `State` looks more like this:
```js
export interface State {
  group: {
    someOtherState: string;
  };
  dynamicForm: FormArrayState<DynamicObject>;
}
```
My `validateForm` function looks like this:
```js
1. const validateForm = (_, state) => {
2.     return updateGroup<State>({
3.         group: updateGroup<State['group']>({
4.              someOtherState: validate(required),
5.         }),
6.         dynamicForm: updateArray(
7.             updateGroup<DynamicObject>({
8.                 someNumber: validate(required, greaterThan(0)),
9.             })
10.        )
11.    });
12. };
```
However, this does not compile if I include lines 6-10, any idea what's going on? The long error message ends with:
```
is not assignable to parameter of type 'StateUpdateFsn<State>[]'
```

**Comment by BovineEnthusiast** [comment]
@MrWolfZ Is my understanding correct in that `createFormArrayState` should _not_ be nested inside a `createFormGroupState`? e.g. if I have a form that has a dynamic set of fields, the dynamic fields' state should be kept at the same level as the overall form:

```ts
// 🚫
form: FormGroupState<{
  dynamicControls: FormArrayState<SomeType>,
  // other controls
  // ...
}>
```

vs

```ts
// ✅
form: FormGroupState<{
  // other controls
  // ...
}>,
dynamicControls: FormArrayState<SomeType>,
```

**Comment by MrWolfZ** [comment]
@BovineEnthusiast neither, the correct version would be

```ts
form: FormGroupState<{
  dynamicControls: SomeType[],
  // other controls
  // ...
}>
```

All form state types are recursively resolved to the correct type, i.e. in the example above `form.controls.dynamicControls` is of type `FormArrayState<SomeType>`.

**Comment by BovineEnthusiast** [comment]
Gotchya,

I have (probably) one more question:

After thinking about it I've realized that I have a different type of dynamic form. In my case, there is a specific control that can change. Think like a "for sale" form where a "details" section changes depending on what you're selling. I'm thinking that I'd have an action that replaces the control depending on the sale type. Then, since the [`updateFn`](https://github.com/MrWolfZ/ngrx-forms/blob/b43bda8ea780a48cb2d8a5b27217bb0558e302cd/src/reducer.ts#L147) receives the state, I can determine which validation to use. Does this sound like the "proper" way to do this in the library?

Thanks for taking the time to answer these questions and thanks again for the library!

**Comment by MrWolfZ** [comment]
@BovineEnthusiast depending on how complex the non-details part of the form is I would consider just replacing the whole form instead of just the details part, since I am honestly not sure how well something like this would work:

```ts
interface ForSaleFormValue {
  id: string
  details: CarDetailsFormValue | HouseDetailsFormValue
}
```

You would probably have to do a lot of ugly type casting and also the form shape inference may not work properly when completely switching out the control for the details. The alternative design could be with generics, e.g.

```ts
interface ForSaleFormValue<TDetailsFormValue> {
  id: string
  details: TDetailsFormValue
}

type CarForSaleFormValue = ForSaleFormValue<CarDetailsFormValue>
type HouseForSaleFormValue = ForSaleFormValue<HouseDetailsFormValue>
```

Then you can distinguish between these on a whole form level, which should probably work much better.

**Comment by BovineEnthusiast** [comment]
Seems like the generic route worked!

The only downside is since I'm replacing the entire form I lose all status state (e.g. touched). Not a big deal though since the detail choice happens in the first step. Did have to revalidate the form though.

**Comment by MrWolfZ** [comment]
Closed due to inactivity.
