### ISSUE TITLE
Form Array with nested objects

### ISSUE THREAD

**Issue by abannsunny** [MrWolfZ/ngrx-forms#160]
Hi,
I have been enjoying using this library. Thank you!

We ran into an issue with FormArrayState with nested objects.

I have a form with a structure like this:

```
export interface MyFormValue {
  stringValue: string;
  myArray: MyArrayForm[]
}

export interface MyArrayForm {
  val1: string
  nestedObject: MyArrayNested
}

export interface MyArrayNested {
  val2: string
}
```
the nestedObject could be null or it could have an object value. My data looks like this :

```
{
  stringValue: "",
  myArray: [
    {
      nestedObject: null,
      val1: "element 1"
    },
    { 
      nestedObject: {
        val2: 'element 2'
      },
      val1: ''
    }
  ]
}
```
and I am trying to remove/add/update items in the array using the setValue method. like so:
```
state = updateGroup<MyFormValue>(state, {
        myArray: (control, form) => setValue( control, newArray)
      })
```
with a datastructure like the one above if I remove the first element with  nestedObject with value null I get the following error.

Error: Form control states only support undefined, null, string, number, and boolean values as well as boxed values; got {"val2":"element 2"} of type object

Is this expected behavior? if yes am I using the setValue in a case where its is not advised to be used?

#### Could you please suggest what the right approach is, in this case?

I have a reproduction of the issue:
https://stackblitz.com/edit/angular-ejrtus

if the datastructure is like so:
```
        { 
      nestedObject: {
        val2: 'element 2'
      },
      val1: ''
    },
    {
      nestedObject: null,
      val1: "element 1"
    },
```
this happens:

ERROR
Error: Cannot convert undefined or null to object

I was expecting the array to be created when calling setValue on the array rather than an update.

The work around we are using right now is the delete the key on the object if the value is null

```
delete myArrayForm.nestedObject;
```
Thank you

**Comment by MrWolfZ** [comment]
First of all, thank you for the reproduction.

And yes, this is an edge case the ngrx-forms does not handle well. Since ngrx-forms uses the value of a control to infer its type and `null` is considered to be a form control, not a group, you get the behavior you observed. I am honestly not sure if there is a way to fix this without fundamentally changing the way ngrx-forms work.

For this particular scenario there may be an alternative way to achieve this by not using `setValue` to remove the array control but instead use `removeArrayControl` to remove the element at the specific index (you can also just dispatch a `RemoveArrayControlAction` with the id of the array element).

However, I can also propose a different workaround. Instead of using `null` as the value, use the [null object pattern](https://en.wikipedia.org/wiki/Null_object_pattern), i.e. create a default value of `nestedObject` that indicates the value is not present. There are many ways to achieve this:

- you could just set `val2` to `null` (or any other field)
- you could create a (virtual) control `isPresent` on `nestedObject` with `boolean` value
- you could use a user-defined property on each array element

Which one you choose is just personal preference I'd say.

Sorry I can't give you a better answer than this.

**Comment by abannsunny** [comment]
Thank you for the response, I appreciate the thoughtful reply. 
I think I am going to go down the removeArrayControl path.
