### ISSUE TITLE
Including ReactiveFormsModule and NgrxFormsModule in angular 8 doesn't work

### ISSUE THREAD

**Issue by dkowis** [MrWolfZ/ngrx-forms#172]
All you have to do is import the ReactiveForms module ahead of the NgrxForms module, as described in the docs.

1. ng cli 8.x
1. ng new sample
1. ng add @ngrx/store
1. npm install ngrx-forms
1. import the ReactiveFormsModule ahead of NgrxFormsModule
1. create a form
1. Reach this explosion:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/28048/71697215-e6d2f100-2d7c-11ea-80a7-ca8ef577c923.png">

Sample application: https://github.com/dkowis/ngrx-test/tree/reactive-forms-fail

**Comment by MrWolfZ** [comment]
This has nothing to do with **ngrx-forms** (you can see the same error if you remove all **ngrx-forms** code from your example). The problem is how you use angular forms. If you only use reactive forms, you need to bind the form to a form group. Alternatively, you can just also import the `FormsModule` in addition to the `ReactiveFormsModule` which will cause the form to fall back to a template form (at least that's what I believe, I haven't used angular forms in ages due to ridiculous issues like this).
