### ISSUE TITLE
Composing custom and built-in reducers / howto

### ISSUE THREAD

**Issue by pajarito80** [MrWolfZ/ngrx-forms#18]
I've built a reducer function that composes a custom and a built-in ngrx/forms reducer. The reason for that is to have some updates done before the state is handled by the built-in reducers. 

Therefore, I created two custom reducers:

- formPrepareReducer (This reducer function clears any error in the control after the touched, dirty or setValue action is called. This function must be called before any other ngrx/forms reducer.)

- formReducer (This is the replacement of the default formGroupReducer. Instead of formGroupReducer, the custom formReducer is called)

The code looks like this:

```
// The prepare reducer has to be called before the other reducers
function formPrepareReducer<T>(formGroupState: FormGroupState<T>, action: any) {
    switch (action.type) {
        case MarkAsTouchedAction.TYPE:
        case MarkAsDirtyAction.TYPE:
        case SetValueAction.TYPE:
            return formGroupReducer(formGroupState, new SetErrorsAction(action.controlId, {}));
    }
    return formGroupState;
}

// The formReducer replaces the formGroupReducer, beeing used in the main reducer
export function formReducer<TValue extends object>(...updateFnsArr: Array<StateUpdateFns<TValue>>) {
    return (state: FormGroupState<TValue>, action: any) =>
        compose<FormGroupState<TValue>>(
            s => formPrepareReducer(s, action), // calls the prepare reducer first
            s => formGroupReducer(s, action), // calls the default form group reducer second
            updateGroup<TValue>(...updateFnsArr) 
        )(state);
}
```

Altough the above code is working (I haven't tested it with 2.0), I'm wondering if there is a more efficient solution to compose reducers, especially in version 2.0 of ngrx/forms.

Thank you very much for your help in advance.

**Comment by MrWolfZ** [comment]
Let me see if I understand the semantics of your use case correctly. You want the form field to be invalid as long as it has never been touched, or made dirty (setting the value will also mark the control as dirty)? If that is correct I would recommend modeling it differently. Instead of modeling it as a causal relationship (i.e. if X happens, then Y should happen) you can express this as an invariant through update functions by creating a state update function that forces the errors to be empty if isDirty or isTouched is true. However, if you still need to validate the field otherwise there is really no reason to manually clear the errors before the state update runs, since all updates are always applied, regardless of what changed in the state.

However, more generally if you want to apply custom state updates before the form reducer itself runs I believe you have found the optimal solution.

If you could explain your use case with more context I may be able to supply a better answer.

**Comment by pajarito80** [comment]
Thank you very much for your response.

The clearing of the errors is nececessary because we use a combination of client side and server side validation. After submitting the form to the server via effects, the server validates the input and, if the form is invalid, returns a validation error array back to the client.

In the effects we call a custom formErrorReducer (see code below). In this reducer function, the server validation errors will be applied as a new error property 'serverValidation' to the corresponding control state. This property and its value will remain there. The property will not be cleared by ngrx/forms itself after a change value action or a touched action because no client side validator will overwrite this custom property and its value (which is correct in my opinion).

Therefore, we need to clear those errors in case the user changes the value of the field or if the user touches the field. 

I'll try the updateRecursive of version 2.0, but clearing of the errors is still needed, I guess.

Code:
```
/**
 * This reducer method is called after a partly successfully submit of data. If the response of the
 * submit contains validation errors, this method has to be called.
 * It enriches the form state with the validation errors and sets the corresponding states.
 *
 * @param formGroupState
 * @param validationErrorDto
 */
export function formErrorReducer<T>(formGroupState: FormGroupState<T>, validationErrorDto: ValidationErrorDto) {
    if (validationErrorDto.ValidationResults) {
        let newState = Object.assign({}, formGroupState);
        validationErrorDto.ValidationResults
            .map((validationResult: EntityValidationResultDto) => validationResult.ValidationErrors)
            .map((validationErrors: EntityValidationErrorDto[]) => {
                validationErrors.map(validationError => {
                    const propertyName = StringUtils.camelize(validationError.PropertyName);
                    newState = formGroupReducer(newState, new SetErrorsAction(`${formGroupState.id}.${propertyName}`, {
                        'serverValidation': validationError.ErrorMessage
                    }));
                });
            });
        return formAfterSubmitErrorReducer(newState);
    }

    return formAfterSubmitErrorReducer(formGroupState);
}

function formAfterSubmitSuccessReducer<T>(formGroupState: FormGroupState<T>): FormGroupState<T> {
    let newState = markAsSubmitted(formGroupState);
    newState = markAsUntouched(newState);
    newState = markAsPristine(newState);
    return cast(newState);
}

function formAfterSubmitErrorReducer<T>(formGroupState: FormGroupState<T>): FormGroupState<T> {
    let newState = markAsSubmitted(formGroupState);
    newState = markAsUntouched(newState);
    return cast(newState);
}

```

**Comment by MrWolfZ** [comment]
Hmm, I understand your use case now. That's actually a pretty common pattern to want to clear errors once the value changes after a validation. I think your solution is just fine, but you may be able to make your code a bit less dependent on the internals of ngrx forms by using update functions. I'll type up an example this evening after work.

An alternative solution would indeed be to use updateRecursive. When you set the validation errors from the server you can simply always mark the control as untouched and pristine and then clear the errors of all controls who are touched or dirty (since changing the value will always mark the control as dirty). Alternatively you could also store the original value that caused the error as a property on the error object together with the message. Then, inside updateRecursive you can compare the control’s current value with the error value and clear the error if it is different.

As you can see there are a lot of ways to do what you want. Neither is really better or worse. They are all just different ways to achieve the same thing, so it comes down to preference which option you choose.

**Comment by pajarito80** [comment]
Thank you for your suggestions and alternatives to solve this problem. 
It would be great if you could give me an example of using update functions to decrease the dependenies of ngrx forms internals. Appreciate that a lot!

**Comment by MrWolfZ** [comment]
Sorry, didn't get around to creating the example yesterday. So here it is. What this is doing is creating a form group update object that can be passed to `updateGroup` instead of calling the reducer with an action. I haven't actually compiled this, so no guarantee it's error free.

```typescript
export function formErrorReducer<T>(
  formGroupState: FormGroupState<T>,
  validationErrorDto: ValidationErrorDto,
) {
  if (!validationErrorDto.ValidationResults) {
    return formAfterSubmitSuccessReducer(formGroupState);
  }

  const updateFns = 
    validationErrorDto.ValidationResults
      .map(validationResult => validationResult.ValidationErrors)
      .reduce((arr, validationErrors) => [...arr, ...validationErrors], [])
      .reduce((aggregate, validationError) => {
        const propertyName = StringUtils.camelize(validationError.PropertyName);
        const error = {
          serverValidation: validationError.ErrorMessage,
        };
        return Object.assign(aggregate, { [propertyName]: setErrors(error) });
      }, {} as any);

  const newState = updateGroup<T>(formGroupState, updateFns);
  return formAfterSubmitErrorReducer(newState);
}
```

**Comment by pajarito80** [comment]
Sorry for my late reply, I haven't been working on the project for a couple of days and couldn't test it. The function works very well, I replaced the former one with yours.
Thank you very much!
