### ISSUE TITLE
boxed values and undefined properties

### ISSUE THREAD

**Issue by alex-vg** [MrWolfZ/ngrx-forms#186]
At first, thanks for all the work. I'm using this project excessively and like it a lot. 

But there is one thing that I think is a bit weird with boxed values. There is a deepEqual check to make sure a boxed value is kinda the same after serialization and deserialization. But it currently complains about undefined values, which are not that bad.
Accessing an undefined value after serialization and deserialization still results in an undefined value, the only diffrence is that the serializer also drops the key for size reasons.

I made an [example here](https://codesandbox.io/s/ngrx-forms-base-e10n1). Edit the value and it screams to fix it.

Don't get me wrong, I do understand the difference between a not defined property and a property that is set to undefined. It just does not matter here and it produces some errors that I often need to work around.

**Comment by MrWolfZ** [comment]
Hmm, yeah, this is a tricky one. The whole serialized string equality check to check for serializability is indeed a bit hacky. It's just the simplest solution for this instead of having to recursively enumerate all properties to check if they are of a serializable type.

I see two options here: write a better explicit serializability check or use a custom replacer and reviver during the JSON serialization to keep `undefined` values in the object (e.g. by replacing them with the string "$ngrx-forms:undefined" or something else that is highly unlikely to ever actually be used by a user).

I think this is a good candidate for a first PR. Do you want to try your hand at it?

**Comment by alex-vg** [comment]
@MrWolfZ did you already look at the pr? Any thoughts?

**Comment by MrWolfZ** [comment]
Apologies for leaving this issue unresolved for such a long time. I have just released version [6.3.1](https://github.com/MrWolfZ/ngrx-forms/releases/tag/v6.3.1) which contains a fix for this issue.
