### ISSUE TITLE
Updating Dependant Field

### ISSUE THREAD

**Issue by andypleasants** [MrWolfZ/ngrx-forms#207]
Hi, first of all, great library - saved me a lot of work in the past year!

I'd just like to check if I am doing this correctly:

My form structure looks like this:

```typescript
interface Quote {
    lines: {
        product: string,
        price: number
        .......
    }[]
    .......
}
```
When I set the product field (by using a select field) I hook into SetValueAction to set the value of price based on a lookup table; I think replace the appropriate control like so:

```typescript
export const reducer = createReducer(
    initialAppState,
    onNgrxForms(),
    onNgrxFormsAction(SetValueAction, (state, action) => {
        const p = initialAppState.products.find(p => p.value === action.value);
        const control = createFormControlState(action.controlId.replace(/product$/, 'price'), 0); //to make sure I get the correct "row" in the array (i.e. FORM.lines.0.price)
        const st = setValue(p.price)(control);
        state.form = updateRecursive(state.form, s => s.id === st.id ? st : s); 
        return state;
    })
);
```
This does work, but is it the best way to do it?

p.s. I have removed some checks to make sure it really is the `product` field that is being updated for simplicity.

**Comment by MrWolfZ** [comment]
Thanks for using the library and sorry for the late response ;)

I think your solution is actually rather elegant. Even though I generally recommend against manipulating control IDs like this because they are an implementation detail, I'd say at this point it is very unlikely I will ever change their structure.

One thing you lose with this code is the previous metadata of the price control like `isDirty` etc. (which probably even makes sense). The "proper" way of doing it would be a `findControlById` function that parses the ID and finds the correct control in the form state.

Two things I noticed about your code:

1. You can just pass `p.price` as the initial value of the control, instead of using `setValue`
2. I haven't used `ngrx` in quite some time, but shouldn't the `state` parameter be immutable? i.e. you should `return { ...state, form: ... }` instead of mutating it

I'll close this issue for now but feel free to continue posting here if you have more comments/questions
