### ISSUE TITLE
[Question] use of $obv | async as on templates

### ISSUE THREAD

**Issue by snakone** [MrWolfZ/ngrx-forms#219]
Hello, I'll be using this library on my project, i've been seen your docs i find out something weird on the html example app.

You are using many **| async** pipes

it wouldnt be better to use the syntax **$obs | asyn as obv**?

then later **obv.control.value**

**Comment by MrWolfZ** [comment]
Yes, absolutely. I have written most of this lib and the docs before the `async as` syntax existed, which is why I didn't use it. Since I am not actively developing the library anymore (i.e. I'm just doing bugfixes and compatibility changes), I haven't bothered updating those `async` pipe usages. Pull requests are always welcome though.

**Comment by MrWolfZ** [comment]
Closed due to inactivity.
