### ISSUE TITLE
angular LSP causes an error when directives ngrxFormState or ngrxFormControlState are used

### ISSUE THREAD

**Issue by 0x450x6c** [MrWolfZ/ngrx-forms#225]
New angular LSP with --experimental-ivy enabled has diagnostic INLINE_TYPE_CTOR_REQUIRED.

It causes an error when directives ngrxFormState or ngrxFormControlState are used, and whole file become unusable for LSP.

See: https://github.com/angular/angular/blob/9a5ac47331faf0f6030bff75ad8ef8dab2f8d2d9/packages/compiler-cli/src/ngtsc/typecheck/src/context.ts#L283-L298

Workaround: https://github.com/0x450x6c/ngrx-forms/commit/ac88d5da2426785d67d74366b1c40ab0612b1049

**Comment by MrWolfZ** [comment]
Unfortunately, I'm not sure how I can reproduce this. The code change you linked points to the `@angular/compiler-cli` package. I upgraded the example app to version `11.1.0-rc.0`, but everything still works.

However, even though the link points to `@angular/compiler-cli`, you mention that the issue is in the language service. I am using VSCode and the angular language service plugin references an older version of the language service (`11.0.3`). This version works just fine. When I manually point it to `11.1.0-rc.0` the plugin completely stops working, even in files without any reference to ngrx-forms.

How did you test/find this issue?

**Comment by 0x450x6c** [comment]
@MrWolfZ 

Steps to reproduce:
1. Install latest vscode extension `11.1.0-rc.1`.
2. Enable experimental ivy in the extension settings.
3. Clone repo https://github.com/0x450x6c/ngrx-forms-bug-report-225
4. Run `npm install` and `npx ngcc`.
5. Open project `src/app/app.component.html` in vscode. https://i.imgur.com/TFsvgSE.png

**Comment by MrWolfZ** [comment]
Alright, thank you. I was able to reproduce and fix the issue. Version [6.3.4](https://github.com/MrWolfZ/ngrx-forms/releases/tag/v6.3.4) contains the fix.
