### ISSUE TITLE
New user requires review

### ISSUE THREAD

**Issue by sylvaingirardbe** [MrWolfZ/ngrx-forms#27]
Hi,

I'm trying to implement ngrx-forms into an application I'm working on and so far everything is working and  a whole bunch of code has been removed or moved from components to reducers, which is great. Before I continue the implementation I'd like a quick review of the way I'm working since I'm not 100% sure it's done the way it should be done, especially the validation and adding/updating addresses. The reason for the unusual approach with address is because there is only 1 form for adding/editing them and not a form per address.

```typescript
export const FORM_ID = 'asset';
export const SUBADDRESSFORM_ID = 'asset_address';

export interface State {
    currentSubaddress: FormGroupState<AssetAddress>;
    formState: FormGroupState<Asset>;
}

const initialState: State = {
    currentSubaddress: undefined,
    formState: createFormGroupState<Asset>(FORM_ID, new Asset())
};

const validationFormGroup = updateGroup<Asset>({
    location: updateGroup<AssetLocation>({ 
        address: updateGroup<AssetAddress>({ 
            countryCode: validate(required) 
        })
    })
});

const assetFormReducer = createFormGroupReducerWithUpdate<Asset>({
    location: updateGroup<AssetLocation>({ 
        address: updateGroup<AssetAddress>({ 
            countryCode: validate(required) 
        })
    })
  });

export const addOrReplaceAddressInAssetIdentification = (asset: Asset, address: AssetAddress): Asset => {
    const addressIndex = asset.identification.addresses.findIndex(c => c.id == address.id);
    let newAddresses: AssetAddress[];
    if(addressIndex != -1) {
        newAddresses = [
            ...asset.identification.addresses.slice(0, addressIndex),
            address,
            ...asset.identification.addresses.slice(addressIndex + 1)
        ];
    }
    else {
        newAddresses = [
            ...asset.identification.addresses,
            address
        ];
    }

    return new Asset({
        ...asset,
        identification: new AssetIdentification({
            ...asset.identification,
            addresses: newAddresses
        })
    });
}

export function reducer(state = initialState, action: assetDetail.All): State {
    state = {
        ...state,
        formState: assetFormReducer(state.formState, action),
        currentSubaddress: state.currentSubaddress != undefined ? formGroupReducer(state.currentSubaddress, action) : undefined
    };

    switch (action.type) {
        case assetDetail.SAVE_SUBADDRESS:
            const addressToSave = state.currentSubaddress.value;
            const currentAsset = state.formState.value;

            return {
                ...state,
                currentSubaddress: undefined,
                formState: validationFormGroup(createFormGroupState<Asset>(FORM_ID, addOrReplaceAddressInAssetIdentification(currentAsset, addressToSave)))
            }
        case assetDetail.DONE_WITH_SUBADDRESS:
            return {
                ...state,
                currentSubaddress: undefined
            }
        case assetDetail.EDIT_SUBADDRESS:
            return {
                ...state,
                currentSubaddress: createFormGroupState<AssetAddress>(SUBADDRESSFORM_ID, action.payload.value)
            }
        case assetDetail.ADD_SUBADDRESS:
            return {
                ...state,
                currentSubaddress: createFormGroupState<AssetAddress>(SUBADDRESSFORM_ID, new AssetAddress())
            }
        case assetDetail.LOAD_COMPLETE:
            return {
                ...state,
                progress: new Set<string>(),
                formState: validationFormGroup(createFormGroupState<Asset>(FORM_ID, action.payload))
            };
        default:
            return state;
    }
}
```

Thanks in advace for your time!

**Comment by MrWolfZ** [comment]
Hi @sylvaingirardbe, it's always nice to see new people trying out the library.

I like your code, and there isn't much that I would to different. Here are a couple of points:

1. I don't use classes but just plain objects (with an interface) for form values. While classes seem to work just fine, internally ngrx-forms has no logic to preserve the class identity of the object. Instead, it will always copy over the properties into new plain objects. That means `formState.value` is not an instance of `Asset` which may cause issues if you use e.g. `instanceof` or expect the value to have some class method. However, as long as you are aware of these potential issues it's just fine to keep using classes.
2. I noticed that the address validation is not running on the current sub address all the time but only once it is saved as part of the asset. I am not sure if this is what you intended. In any case, you can remove a bit of redundancy by declaring some more (admittedly verbose) helper methods like this. It uses the (a bit unfortunately named) `StateUpdateFns` interface from ngrx-forms.

```typescript
const assetAddressFormStateValidationUpdateFns: StateUpdateFns<AssetAddress> = { 
  countryCode: validate(required)
};

const validateAssetAddressFormState = updateGroup(assetAddressFormStateValidationUpdateFns);
const assetAddressFormStateValidationReducer = createFormGroupReducerWithUpdate(assetAddressFormStateValidationUpdateFns);

const assetFormStateValidationUpdateFns: StateUpdateFns<Asset> = { 
  location: updateGroup<AssetLocation>({ 
    address: validateAssetAddressFormState
  })
};

const validateAssetFormState = updateGroup(assetFormStateValidationUpdateFns);
const assetFormStateValidationReducer = createFormGroupReducerWithUpdate(assetFormStateValidationUpdateFns);

// and then in your reducer as you did before:
state = {
  ...state,
  formState: assetFormStateValidationReducer(state.formState, action),
  currentSubaddress: state.currentSubaddress != undefined ? assetAddressFormStateValidationReducer (state.currentSubaddress, action) : undefined
};
```

3. Not related to ngrx-forms: In `addOrReplaceAddressInAssetIdentification` you can shorten the code quite a bit by using `splice` instead of `slice`. This should do the same:

```typescript
export const addOrReplaceAddressInAssetIdentification = (asset: Asset, address: AssetAddress): Asset => {
  const addressIndex = asset.identification.addresses.findIndex(c => c.id == address.id);
  const newAddresses = asset.identification.addresses.splice(addressIndex, 1, address);

  return new Asset({
    ...asset,
    identification: new AssetIdentification({
      ...asset.identification,
      addresses: newAddresses
    })
  });
}
```

As I mentioned above, none of these points are mandatory and your code is fine without these changes. I'll keep this issue open in case you have more questions. Feel free to close it yourself once you are confident you have achieved what you want.

PS: I edited your post to include syntax highlighting which makes it easier to read.

**Comment by sylvaingirardbe** [comment]
Ok, thanks a bunch for the feedback. I was aware of No.1. No.2, not so much. I'll update my code a bit, same for No.3.

**Comment by sylvaingirardbe** [comment]
I've come across something else now. I can't seem to figure out how to disable a control. The examples about disabling controls are disabling entire control groups and not just specific controls in a group.

**Comment by MrWolfZ** [comment]
Just leave away the parentheses on `disable`. Strange though that it compiles like this. I'll need to have a look at the typings.

**Comment by MrWolfZ** [comment]
@sylvaingirardbe did this resolve your issue? Can I close this?

**Comment by sylvaingirardbe** [comment]
Yep, thanks. I'll reopen when I come across something else.
