### ISSUE TITLE
Issue with updating values and back to previous values via actions (for eg, time travel with dev tools)

### ISSUE THREAD

**Issue by nathanmarks** [MrWolfZ/ngrx-forms#3]
One more issue I've encountered -- when traveling back in time using the dev tools, the `<select>` element only updates the selected option once, despite the value changing correctly in the store if I output the control value to the template directly.

**Comment by nathanmarks** [comment]
@MrWolfZ This is where the `writeValue()` call is getting filtered out:

https://github.com/MrWolfZ/ngrx-forms/blob/master/src/control/directive.ts#L115

**Comment by nathanmarks** [comment]
@MrWolfZ this can also be reproduced using an `<input>` if you enter a character and delete it (repeat that a few times) and then try to time travel.

**Comment by nathanmarks** [comment]
It's because the `lastViewReportedValue` is not updated when state is controlled via the store, which is what happens when time traveling with the dev tools.

**Comment by nathanmarks** [comment]
@MrWolfZ What do you think to changing `lastReportedViewValue` to `lastReportedValue` and also updating it when the value is set by the state rather than user input? I think that by setting it after [calling `writeValue()` ](https://github.com/MrWolfZ/ngrx-forms/blob/master/src/control/directive.ts#L116) will solve this issue.

**Comment by MrWolfZ** [comment]
@nathanmarks excellent suggestion. That's exactly what I had in mind. I'll call it `latestKnownViewValue` and it should fix your issue. The problem is event worse than just time travel since if you change the view value to `'A'`, then change the state to `'B'` and back to `'A'` the second change will not be applied since it matches the last value reported by the UI. I'll fix this tomorrow (it's almost midnight here).

**Comment by MrWolfZ** [comment]
I fixed this issue in version 1.0.2 which I just released.
