### ISSUE TITLE
No provider for ControlContainer

### ISSUE THREAD

**Issue by meechy79** [MrWolfZ/ngrx-forms#30]
I am trying to replace some form code within my project to use ngrx-forms but am having the following template parsing error.  Do you have any idea what I am missing?

**No provider for ControlContainer ("  [ERROR ->]<form class="builder" [ngrxFormState]="formState$ | async">
    <mat-tab-group>
        <mat-tab la"): ng:///QueryBuilderModule/QueryBuilderComponent.html@0:2
Error: Template parse errors:
No provider for ControlContainer ("  [ERROR ->]<form class="builder" [ngrxFormState]="formState$ | async">
    <mat-tab-group>
        <mat-tab la"): ng:///QueryBuilderModule/QueryBuilderComponent.html@0:2**

**Comment by MrWolfZ** [comment]
Hmm, doesn't sound like it has something to do with ngrx-forms. It contains no class called `ControlContainer`.

It sounds a bit like [this issue](https://github.com/angular/angular/issues/10251). Do your form elements still have the `formControlName` attributes? If so you need to remove them and replace them with the proper `ngrxFormControlState`.

**Comment by meechy79** [comment]
Thanks for the swift reply.  
I do not have any other forms directives other than those supplied by ngrx-forms. I do however have other modules within the application still using ReactiveForms.  Do you think I need to commit the entire application to using ngrx-forms rather than this particular form? I was hoping to replace all over the next few iterations and not commit to a larger refactoring task.

**Comment by meechy79** [comment]
My form is also getting quite complex which means I do have separate child components which actually contain the ngrxFormControlState directive.  Do you have any examples of doing this or do you require all form field to be on the same template?  This behaviour works fine with ReactiveForms.

**Comment by MrWolfZ** [comment]
No, you can freely pass states around to child components. In the application I am working on we have forms that are ten levels deep with hundreds of form controls split over many many components. It should also be possible to mix ngrx-forms with reactive forms. However, the error clearly indicates that there is an issue with something related to reactive forms. If you have complex forms maybe there is some child component that is still using a reactive forms attribute and is looking for a form group in its ancestry? I would recommend debugging the javascript at the point the error is thrown and then backtrack through the stacktrace to find out which class cannot be instantiated due to the missing dependency. It will probably be some instance of reactive form's FormControl which may then contain a reference to the HTML element, which will tell you exactly which element is causing the issue.

**Comment by meechy79** [comment]
I solved it, I still had the ReactiveFormsModule imported into the module that contains this template and ngrx-forms.  It must be trying to take over how the <form/> element is used and/or compiled.

**Comment by MrWolfZ** [comment]
Glad to hear you could resolve the issue.

**Comment by portothree** [comment]
I know that's a really old issue, but if anyone is experiencing it nowadays, you can fix it with `ngNoForm` to the `<form>` tag without the need to remove ReactFormsModule from the module.

**Comment by MaximeKoitsalu** [comment]
> I know that's a really old issue, but if anyone is experiencing it nowadays, you can fix it with `ngNoForm` to the `<form>` tag without the need to remove ReactFormsModule from the module.

This solved my issue, thanks!!
