### ISSUE TITLE
Reducer Decorator

### ISSUE THREAD

**Issue by Kaffiend** [MrWolfZ/ngrx-forms#38]
Curiosity - Question
@MrWolfZ This seems very superficial and purely cosmetic, but I'm curious. Would it be possible to attach the form reducer methods with their own Decorator instead of the current spreading before the switch?

**Comment by MrWolfZ** [comment]
Sure. The spread before the switch is just one way of doing it. You could write a decorator that takes the name of the form state as a parameter and calls the `formGroupReducer` on that form state before calling the wrapped reducer.

Personally I have written a helper function `callNestedReducer` to which I pass a reducer and the name of a state property which does the reducer application, equality checks and state update at once so that it is only one line of code in the calling reducer.

```typescript
import { Action, ActionReducer } from '@ngrx/store';

export function callNestedReducer<TState, TNestedStateKey extends keyof TState>(
  state: TState,
  nestedStateKey: TNestedStateKey,
  reducer: ActionReducer<TState[TNestedStateKey]>,
  action: Action,
): TState {
  const oldValue = state[nestedStateKey];
  const newValue = reducer(oldValue, action);

  if (oldValue === newValue) {
    return state;
  }

  return Object.assign({}, state, { [<any>nestedStateKey]: newValue });
}
```

You could of course also use `combineReducers`. With that you would simply use the `formGroupReducer` for the form state and the rest is handled by `combineReducers`. Have a look at [this reducer](https://github.com/MrWolfZ/ngrx-forms/blob/master/example-app/src/app/simple-form/simple-form.reducer.ts) in the example app for how to do it.

**Comment by MrWolfZ** [comment]
@Kaffiend did this answer your question? may I close this issue?

**Comment by Kaffiend** [comment]
absolutley
