### ISSUE TITLE
subsequent focus actions

### ISSUE THREAD

**Issue by Kaffiend** [MrWolfZ/ngrx-forms#39]
I'm firing off the below effect to reset the form and set focus, it works for the first submit, but all subsequent the focus action dispatches but the control is not focused.

```
  @Effect({dispatch: false})
  addDistrictSuccess$ = this.actions$
  .ofType(districtActions.DistrictActionTypes.AddDistrictSuccess)
  .do(() => {
    this.actionSubject.next(new FocusAction(districtForm.initialFormState.controls.districtName.id));
    this.actionSubject.next(new SetValueAction(districtForm.initialFormState.id, districtForm.initialFormState.value));
    this.actionSubject.next(new ResetAction(districtForm.initialFormState.id));
  });
```

**Comment by MrWolfZ** [comment]
Have you added `[ngrxEnableFocusTracking]="true"` to the control in HTML? Only if this is set will the form control directive properly track focus changes. Without this what will happen is exactly what you observe. You focus the element once, but in the state it never becomes unfocused. And therefore it will not focus the element the second time since it thinks it is still focused.

**Comment by Kaffiend** [comment]
I agree with the opt in, if i'm understanding correctly. Majority of forms you only have one or two focus events you want to track usually on reset to go back to the beginning and such. That also fixed the issue, thank you.
