### ISSUE TITLE
Angular service extension typing error in vscode

### ISSUE THREAD

**Issue by patricknazar** [MrWolfZ/ngrx-forms#48]
Hi just got started with the library, it's good. Just a small issue:

[This line](https://github.com/MrWolfZ/ngrx-forms/blob/0fe658c5c0bacdc7c526bd5045d4fd593e089c03/example-app/src/app/dynamic/form/form.component.html#L17) causes an angular service extension error/warning in vscode `[Angular] Identifier 'controls' is not defined. 'AbstractControlState' does not contain such a member` although it does exist and works just fine. Anything I can do about this? Thanks

**Comment by MrWolfZ** [comment]
This is due to a limitation of TypeScript's type system. However, with TypeScript 2.8 we will finally have conditional types which allows me to enhance the typings to correctly infer the type of a child control. Until then all child controls are typed as `AbstractControlState`.

As a workaround ngrx-forms exports a function called `cast`. In your case you just need to expose `cast` as a member on your component and then wrap the form group in such a case, i.e. `[ngrxFormControlState]="cast(formState.controls.group).controls[o]"`.

**Comment by patricknazar** [comment]
Ah ok cool thanks. I think I saw that in the example and was wondering what it was. Thanks for the quick reply again!
