### ISSUE TITLE
Question/Idea about form state dirty values

### ISSUE THREAD

**Issue by patricknazar** [MrWolfZ/ngrx-forms#49]
Is there a way, or should there be a way to to filter `formState.values` for only dirty values? What I am trying to do is take the same array as `formState.value` but where only dirty values exist. I thought of traversing the controls tree for `isDirty` including children. I figured it could be a common task (?) so could be part of the library. Am I following an anti-pattern or any ideas how to achieve this easily?

**Comment by MrWolfZ** [comment]
Hmm, not sure there needs to be a dedicated function for this in the library. You could simply do this: `formState.controls.filter(c => c.isDirty).map(c => c.value)` if you want to get an array of only the values that are dirty.

**Comment by patricknazar** [comment]
Thanks, but I get `formState.controls.filter is not a function` also, what about nested controls? I would need the whole tree of dirty values.

**Comment by patricknazar** [comment]
I've come up with this recursive function to do it. It would be nice to be able to force certain properties on it though, such as `id` or `addresses[x].id` etc. Another reason why I thought making a more powerful/generic function would be good. 

```
filterForDirty(controls) {
    const dirtyTree = {};

    for (const key in controls) {
      if (controls.hasOwnProperty(key)) {
        const value = controls[key];
        if (value.isDirty) {
          dirtyTree[key] = (value.controls ? filterForDirty(value.controls) : value.value);
        }
      }
    }

    return dirtyTree;
  }
```

**Comment by MrWolfZ** [comment]
I see now what you mean. Yes, I think it is possible to create generic map, filter, and reduce functions since form states are as you say just (non-uniform) trees and therefore functors (updateRecursive is already a special case for a map function). They are also monads, although it wouldn't make much sense to define a flatMap over a state. The only tricky part will be the types of the functions, but I think I can make it work.

I'll have a look this evening and post my results here.

**Comment by MrWolfZ** [comment]
Hmm, so I tried out writing `map`, `filter`, and `reduce` functions and it turns out while it is somewhat possible to write them they don't really make much sense in the context of form states after all.

The only thing that kind of works out is `filter` but I feel that the use cases this would be useful for are very rare.

Here is a version of `getFilteredValue` that is a bit more generic and properly typed compared to your version if you want to use it (haven't really tested it, so it might contains bugs).

```typescript
import {
  AbstractControlState,
  FormArrayState,
  FormControlState,
  FormControlValueTypes,
  FormGroupState,
  isGroupState,
  isArrayState,
  KeyValue,
} from 'ngrx-forms';

export function getFilteredValue<T extends FormControlValueTypes>(
  state: FormControlState<T>,
  filterFn: (state: AbstractControlState<T>) => boolean,
): T | undefined;

export function getFilteredValue<T>(
  state: FormArrayState<T>,
  filterFn: (state: AbstractControlState<any>) => boolean,
): T[] | undefined;

export function getFilteredValue<T extends KeyValue>(
  state: FormGroupState<T>,
  filterFn: (state: AbstractControlState<any>) => boolean,
): Partial<T> | undefined;

export function getFilteredValue<T>(
  state: AbstractControlState<T>,
  filterFn: (state: AbstractControlState<any>) => boolean,
): T | undefined;

export function getFilteredValue<T>(
  state: AbstractControlState<T>,
  filterFn: (state: AbstractControlState<T>) => boolean,
): T | Partial<T> | T[] | undefined {
  if (!filterFn(state)) {
    return undefined;
  }

  if (isGroupState(state)) {
    const groupState = state;
    return Object.keys(groupState.controls).reduce((c, key) => {
      const childState = groupState.controls[key];
      const filteredValue = getFilteredValue(childState, filterFn);

      if (filteredValue !== undefined) {
        Object.assign(c, { [key]: filteredValue });
      }

      return c;
    }, {} as Partial<T>);
  }

  if (isArrayState(state)) {
    return state.controls.map(childState => getFilteredValue(childState, filterFn)!).filter(s => !!s);
  }

  return state.value;
}
```

**Comment by MrWolfZ** [comment]
Closing this. If you have any more questions or ideas please feel free to open a new issue.

**Comment by patricknazar** [comment]
Sorry for the late reply, thanks for your efforts.
