### ISSUE TITLE
Question: How to bind to mat-selection-list

### ISSUE THREAD

**Issue by Drammy** [MrWolfZ/ngrx-forms#56]
Hi

I'm having difficulties binding my ngrx-forms formState to a mat-selection-list.  If I bind to the [selected] input the list doesn't display at all.

Any ideas where I'm going wrong?

Model
```
export class ShouldSearchType {
  type: SearchType;
  selected: boolean;
}


export class Search {
  searchPhrase: string;
  searchTypes: ShouldSearchType[];
}
```

Reducer
```
const SearchFormId = 'SearchFormId';
export const InitialSearchFormValue: Search = {
  searchPhrase: '',
  searchTypes: [
    {
      type: SearchType.Project,
      selected: true,
    },
    {
      type: SearchType.Customer,
      selected: true,
    },
    {
      type: SearchType.Person,
      selected: true,
    },
  ],
};
export const InitialSearchFormState = createFormGroupState<FusionSearch>(SearchFormId, InitialSearchFormValue);

export interface State {
  searchForm: FormGroupState<FusionSearch>;
  searchResults: {
    customers: SearchResponse,
    people: SearchResponse,
    projects: SearchResponse
  };
  loaded: boolean;
  loading: boolean;
  error: string | null;
}

export const initialState: State = {
  searchForm: InitialSearchFormState,
  searchResults: {
    customers: null,
    people: null,
    projects: null,
  },
  loaded: false,
  loading: false,
  error: null,
};

const validationFormGroupReducer = createFormGroupReducerWithUpdate<FusionSearch>({
  searchPhrase: validate(required),
});

export function reducer(state = initialState, action: SearchActions): State {

  const searchForm = validationFormGroupReducer(state.searchForm, action);

  if (searchForm !== state.searchForm) {
    state = { ...state, searchForm };
    return state;
  }
...
```

Component
```
export class SearchFiltersListComponent {
  @Input() formState: FormGroupState<Search>;
  @Output() onFilterChanged = new EventEmitter();

  constructor() {
  }

  filterChanged() {
    this.onFilterChanged.emit();
  }

  getSearchType(searchTypeId: number) {
    return SearchType[searchTypeId];
  }
}
```

This view displays the search types correctly, but without the checkboxes bound
```
  <form name="search-filters-form" novalidate
        [ngrxFormState]="formState">

      <mat-selection-list [ngrxFormControlState]="formState.controls.searchTypes">
        <mat-list-option *ngFor="let st of formState.value.searchTypes" [value]="st.type">
          {{getSearchType(st.type)}}
        </mat-list-option>
      </mat-selection-list>
```

...and when I look to bind the checkboxes like below I get nothing displayed at all
```
  <form name="search-filters-form" novalidate
        [ngrxFormState]="formState">

      <mat-selection-list [ngrxFormControlState]="formState.controls.searchTypes">
        <mat-list-option *ngFor="let st of formState.value.searchTypes" [value]="st.type" [selected]="st.selected">
          {{getSearchType(st.type)}}
        </mat-list-option>
      </mat-selection-list>
```

**Comment by MrWolfZ** [comment]
I have update the [material example](https://ngrx-forms-example-app-v2.herokuapp.com/material) in the example app to include a `mat-selection-list` control. Maybe that helps as well.

**Comment by Drammy** [comment]
Hey, no need to apologise - I appreciate the response no matter how late and thanks again for sharing the code in the first place!

Works a treat - thanks very much

**Comment by Drammy** [comment]
I've found that when I navigate away from a component with a mat-selection-list bound as detailed in this thread that A SetValueAction fires and when I return to the component the selected items are now unchecked.

I've search everywhere in my code for the SetValueAction (only 2 hits) and put breakpoints on them and none of these are causing this behaviour.

Is there something in this library that would account for this?

**Comment by Drammy** [comment]
btw: the same behaviour is exhibited in [material example](https://ngrx-forms-example-app-v2.herokuapp.com/material) as well.

**Comment by MrWolfZ** [comment]
Hmm, yes indeed. And I know exactly why it happens since I ran into the same issue when writing my own form value adapters. Basically it's a problem with angular material that I sadly cannot really change easily. 

The problem is this: The `MatListOption` class deselects itself inside `ngOnDestroy` which in turn triggers the containing `MatSelectionList` to update its value. This is all good except that when you navigate away from a page all components on the page get destroyed which in turn triggers the `ngOnDestroy` behaviour for all options and therefore removes all of them from the value of the selection list which then finally reports an empty value to ngrx-forms before being destroyed itself.

When I ran into this issue I went through all the options I can think of but the problem is the order in which components get destroyed. Since the options will always be destroyed before the list itself it is impossible for the list to know whether an option is trying to de-register itself because the whole list is being destroyed as part of the whole page being destroyed or only the option was destroyed. What I finally decided on was to just not deal with the issue at all, meaning if an option gets destroyed it will still be part of the form value.

Therefore, to properly fix the issue angular material would have to fix it. That being said there might be workarounds like for example creating a guard with `canActivate` and `canDeactivate` (the latter of which will run before the page and its content is destroyed) and dispatching marker actions that set some marker property in the state to mark the page as active/inactive. Then finally adjust the reducer that calls the form reducer to only forward form actions when the containing page is active. This is an ugly solution but should work.

**Comment by Drammy** [comment]
Well thanks for taking the time to explain it to me.  Tricky; I like the layout and looks of the mat-selection-list but it does seem to have its problems..

Thanks for the workaround; will have a think...

**Comment by MrWolfZ** [comment]
@Drammy I had an idea this morning and just tried it out and it worked. It is still a hack though. What you can do is apply your own directive to mat list option and use the fact that in the current version of `@angular/material` deselecting the option when it is destroyed is deferred to the end of the current event loop iteration. Therefore you can have some custom code run between the option being destroyed and it trying to report the value. In that code you can overwrite the reference from the option to the list. Long story short: just include the directive below in your project and it should work.

```typescript
import { Directive, Host, Inject, OnDestroy, Optional } from '@angular/core';
import { MatListOption } from '@angular/material/list';

@Directive({
  selector: 'mat-list-option',
})
export class MatListOptionFixDirective implements OnDestroy {
  constructor(
    @Host() @Optional() @Inject(MatListOption) private matDirective: MatListOption | null,
  ) { }

  ngOnDestroy() {
    const dir = this.matDirective;
    if (dir) {
      dir.selectionList = { _reportValueChange: () => void 0 } as any;
    }
  }
}
```

**Comment by Drammy** [comment]
@MrWolfZ Brilliant, thanks.  This works a treat.
Appreciate the follow-up!
