### ISSUE TITLE
Value on select lists replaced by label 

### ISSUE THREAD

**Issue by kmiskiewicz** [MrWolfZ/ngrx-forms#67]
I have a select list like this:
`<select (change)="onChange($event)">`
` <option *ngFor="let event of (events$ | async | orderBy:'id') " [selected]="event.id === (currentEvent$ | async)" [value]="event.id">{{event.name}}</option>`
`</select>`
As a value I assign just ids like 1,2,3, etc. 
As label I assign name of events like "Great Summer 2018" etc. 
In the TS I have nothing more than just regular NGRX selectors:
events$ = this.store.select(getAllEventEntities);
currentEvent$ = this.store.select(getCurrentEventId);

As long as I do not have NgrxFormsModule imported to my module everything works fine. I loaded the module to one of sub modules, not a core module. 
After the import for some reasons value on my list are replaced by... labels. 
In html seems to be fine, <option _ngcontent-c6="" ng-reflect-value="1">BOS 2018</option> 
however the onChange event return the label in the event.target.value:
`  public onChange(event): void {
    const newVal = event.target.value; //label instead of value
`
I tested version 2.3.2 and 2.3.1 with the same result
my package json:
` "dependencies": {
    "@angular-devkit/schematics": "0.4.3",
    "@angular/animations": "5.2.7",
    "@angular/common": "5.2.7",
    "@angular/compiler": "5.2.7",
    "@angular/compiler-cli": "5.2.7",
    "@angular/core": "5.2.7",
    "@angular/forms": "5.2.7",
    "@angular/http": "5.2.7",
    "@angular/platform-browser": "5.2.7",
    "@angular/platform-browser-dynamic": "5.2.7",
    "@angular/platform-server": "5.2.7",
    "@angular/router": "5.2.7",
    "@aspnet/signalr": "1.0.0-preview1-update1",
    "@aspnet/signalr-protocol-msgpack": "1.0.0-preview1-update1",
    "@nguniversal/module-map-ngfactory-loader": "5.0.0-beta.6",
    "angular-oauth2-oidc": "3.1.4",
    "angular2-jwt": "0.2.3",
    "aspnet-prerendering": "3.0.1",
    "core-js": "2.5.3",
    "font-awesome": "4.7.0",
    "preboot": "6.0.0-beta.3",
    "rxjs": "5.5.6",
    "zone.js": "0.8.20",
    "@ngrx/effects": "5.2.0",
    "@ngrx/router-store": "5.2.0",
    "@ngrx/store": "5.2.0",
    "@ngrx/entity": "5.2.0",
    "ngrx-store-freeze": "0.2.1",
    "@ngx-translate/core": "9.1.1",
    "ngrx-store-localstorage": "^0.3.0",
    "@angular/material": "5.1.1",
    "@angular/cdk": "5.1.1",
    "lodash-es": "4.17.4"
  },
  "devDependencies": {
    "@angular/cli": "1.7.4",
    "@angular/compiler-cli": "5.2.7",
    "@angular/language-service": "5.2.7",
    "@angular/service-worker": "5.2.7",
    "@compodoc/compodoc": "1.0.8",
    "@types/jasmine": "2.8.6",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "9.4.6",
    "codelyzer": "4.2.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "1.4.1",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.3.0",
    "ts-node": "5.0.1",
    "tslint": "5.9.1",
    "typescript": "2.6.2",
    "webpack-bundle-analyzer": "2.11.1",
    "@ngrx/store-devtools": "^4.1.1"`

**Comment by MrWolfZ** [comment]
Hmmm, yes, I see what is causing this. The default behaviour of Angular is that if an attribute is bound without a directive that has an @Input defined on that attribute it will simply write its value to the DOM. In your case that means the event's id is correctly written to the `value` attribute of the `option`. However, ngrx-forms adds a directive to the `option` element which has an `@Input()` binding for `value`. The binding is specifically written in a way that it does not modify the DOM element if the `option` is not connected to a ngrx-forms control state. However, what I did not realize is that Angular then stops setting the value as it usually does. Therefore the `value` attribute will not be in the DOM at all and the browser handles these cases by using the option's content as the value which is why you are seeing your event's label being used as the value.

The fix would be to provide another directive that restores the default behaviour of Angular in case the `option` is not used in the context of ngrx-forms. However, it is still not a perfect solution since this directive might in turn conflict with other directives that modify the `value`. However, looking at Angular's source code they are doing something similar. Therefore, even though it is not perfectly safe this solution should be good enough in almost all of situations.

I'll try to create a hotfix package tomorrow.

**Comment by MrWolfZ** [comment]
I have just published version 2.3.3 which contains a fix for this bug.

**Comment by kmiskiewicz** [comment]
Thank you so much :-)!
