### ISSUE TITLE
Documentation for actions

### ISSUE THREAD

**Issue by marcelnem** [MrWolfZ/ngrx-forms#78]
Are the Reducer Actions for ngrx-forms (e.g. SetValue action) documented anywhere? If not, I think it would be good to at least link to a code where the actions are defined as a temporary substitution for the documentation.

**Comment by MrWolfZ** [comment]
In the current version there is no documentation of the actions in the user guide. However, for the next version I have updated the documentation to add examples of how actions can be used to update the state. You can see them [here](http://ngrx-forms.readthedocs.io/en/develop/user-guide/updating-the-state/).

However, the best documentation is the [code itself](https://github.com/MrWolfZ/ngrx-forms/blob/master/src/actions.ts). And since the actions are all declared in one file it is pretty readable. I will add a link to this file to the documentation for the next version.
