### ISSUE TITLE
updateGroup: Build error with TypeScript 2.7.2

### ISSUE THREAD

**Issue by blissi** [MrWolfZ/ngrx-forms#81]
Hallo,

the following little code snippet results in a build error with TypeScript 2.7.2:

```
interface Test {
	id: string
}

const validateTest = updateGroup<Test>({
	id: validate(required)
});
```

The error is:
```
src/app/shipping/Editor/ShippingEditor.validation.ts(16,40): error TS2345: Argument of type '{ id: ProjectFn<AbstractControlState<{}>>; }' is not assignable to parameter of type 'FormGroupState<Test>'.
  Property 'value' is missing in type '{ id: ProjectFn<AbstractControlState<{}>>; }'.
```

It seems as if TypeScript is resolving the overload of updateGroup that takes the form state as the first parameter.

Do you have any suggestion how I can fix this?
I have the latest version of ngrx-forms, 2.3.5.

Thanks,
Steven

**Comment by MrWolfZ** [comment]
Hi Steven, indeed, sadly the typing of the `required` validation function in the current version is sub-optimal. With version three your code will compile. Until then you have to tell the validate function what type it expects, so this code will compile:

```typescript
interface Test {
  id: string
}

const validateTest = updateGroup<Test>({
  id: validate<string>(required)
});
```

The longer explanation is this: Since the `required` function takes a generic `T` or `null` it will infer the validate call in your example to be `validate<string | null>` which then returns a `ProjectFn<AbstractControlState<string | null>>` which does not match the type of the `id` control. Since the overload that takes an update function object is therefore not matching the compiler falls back to the next one which causes the compiler error you see.

**Comment by blissi** [comment]
Wow, thank you for the nearly instant response! 👍 
It works :-)
