### ISSUE TITLE
Plans to move repo to @ngrx/forms to be first class package?

### ISSUE THREAD

**Issue by vincentjames501** [MrWolfZ/ngrx-forms#83]
Was just curious if the folks over at ngrx had any plans to make this a first class package in the ngrx repo. Would love to see this library be more discoverable and encourage everyone to use it!

**Comment by MrWolfZ** [comment]
There is an [issue](https://github.com/ngrx/platform/issues/431) discussing this on the @ngrx repo. You can add a post there. However, from what is written there (and also based on [this tweet](https://twitter.com/robwormald/status/963176746135691264?lang=en)) it is highly unlikely that **ngrx-forms** will ever be merged to the official @ngrx.

In terms of discoverability I am fine with being the top result when googling "ngrx forms".

**Comment by darpankumar** [comment]
@MrWolfZ can you provide your input on this discussion after 2 years now still i could not see any solid reference or best practice to use

**Comment by MrWolfZ** [comment]
@darpankumar please have a look at [this comment](https://github.com/MrWolfZ/ngrx-forms/issues/190#issuecomment-639594141). In the end it is mostly up to personal preference I guess. Personally, I always prefer **ngrx-forms** (sometimes as local forms), simply because I prefer strong type safety and angular forms does not give me that. However, I also understand if people want to stick with the "standard solution".
