### ISSUE TITLE
Struggling to upgrade to 3.x

### ISSUE THREAD

**Issue by philjones88** [MrWolfZ/ngrx-forms#95]
Hey,

I've been reading the release notes, docs and looking again at the sample app but can't figure out how to get our existing ngrx forms reducers into the new approach.

Basically they all do roughly the same thing:

1. update the entire state of the form from a Http request complete action
2. apply validation to the form
3. some custom properties

The examples don't seem to do 1+2+3 together.

Here's an example:

```
export interface State extends McuViewModel {
  changingPassword: boolean;
  newMcuState: McuStates;
}

export function createState(model: State) {
  return createFormGroupState<State>(
    'callbridges',
    model
  );
}

export const initialState = createState({
  ...new McuService(null, null).newMcu(),
  changingPassword: false,
  newMcuState: McuStates.online
});

const validatePasswordsMatch = (state: FormGroupState<State>) =>
  state.value.password === state.value.confirmPassword ? {} : { match: false };

const validationFormGroupReducer = createFormGroupReducerWithUpdate<State>({
  name: validate<string>(required),
  ipAddress: validate<string>(required),
  ipPort: validate<number>([required, greaterThan(0), lessThan(65536)]),
  password: (control, state) =>
    validate<string>(() => validatePasswordsMatch(state), control),
  confirmPassword: (control, state) =>
    validate<string>(() => validatePasswordsMatch(state), control)
});

const customFormGroupReducer = (state: FormGroupState<State>, action: CallbridgeActions): FormGroupState<State> => {
  switch (action.type) {
    case CallbridgeActionTypes.FetchComplete:
      return createState({
        ...action.mcu,
        changingPassword: false,
        newMcuState: action.mcu.mcuState === McuStates.online ? McuStates.online : McuStates.offline,
      });

    case CallbridgeActionTypes.ToggleChangePassword:
      return updateGroup(
        state,
        { password: setValue(undefined) },
        { confirmPassword: setValue(undefined) },
        { changingPassword: setValue(!state.value.changingPassword) }
      );

    case CallbridgeActionTypes.Save:
      return updateGroup(
        state,
        { mcuState: setValue(state.value.newMcuState) }
      );

    default:
      return state;
  }
};

export function reducer(state = initialState, action: CallbridgeActions): FormGroupState<State> {
  state = customFormGroupReducer(state, action);
  state = validationFormGroupReducer(state, action);
  return state;
}
```

any pointers you can give would be much appreciated

**Comment by philjones88** [comment]
Think I've got it. One thing that tripped me up is enums have to be cast to string.

i.e. I have a property of enum type `McuStates` and I had to write the `setValue` like `mcuState: setValue<string>(state.value.newMcuState)`

**Comment by MrWolfZ** [comment]
Hmm, I'll look into the support for enum form values.

Looking at the code there is one other thing that may also cause the state to not be properly validated. In v3 I changed the reducer returned by `createFormGroupReducerWithUpdate` to only apply the update if the form state changed as a result of reducing the action. In your code for example when `CallbridgeActionTypes.FetchComplete`  is encountered it will re-create the form state but not validate it since the form group reducer doesn't know anything about that action and therefore the state doesn't change. In your case I recommend changing your code to make the validation function explicitly called, i.e. instead of `const validationFormGroupReducer = createFormGroupReducerWithUpdate<State>({` use `const validateFormGroup = updateGroup<State>({` and then in `reducer` use `state = validateFormGroup(formGroupReducer(state, action))`. This way your validation is guaranteed to be applied.

**Comment by varrob112** [comment]
Thank you, @MrWolfZ for the validation fix idea!

**Comment by MrWolfZ** [comment]
Having looked into enums I don't think there is a way for me to do this. The workaround as explained by @philjones88 is simple enough though.
