### ISSUE TITLE
Disabled form controls in value

### ISSUE THREAD

**Issue by agalazis** [MrWolfZ/ngrx-forms#99]
I think disabled form controls should not be in the value attribute of their group since they would be disregarded in form submission.

**Comment by MrWolfZ** [comment]
Hmm, I'm not sure if I like this. I know that traditional forms behave like this but in modern SPAs there are many reasons why a form control may be disabled, so this would be a bad default. In addition it would be impossible to type this properly (I would have to change the form value to have all properties optional since the property may be missing due to the control being disabled, which would make the library unusable). However, I'll keep this issue open to track adding a utility function to get the form value without disabled controls.

**Comment by agalazis** [comment]
I understand it would also break other apps/make upgrades more difficult so yes maybe an optionally used selector could do

**Comment by MrWolfZ** [comment]
I have decided that this is too much of an edge case to provide a solution for it within the library. There are also quite a lot of tricky situations like a single control in an array being disabled (should the control be left out of the value array or should it's value be undefined?). I think it is better for anybody that needs this to come up with their own solution.
